### ISSUE TITLE
Non-converging optimization with Hilbert-Schmidt distance

### ISSUE THREAD

**Issue by Basilewitsch** [qucontrol/krotov#42]
By using the Hilbert-Schmidt distance as state overlap measure for a gate optimization employing the 3-states method, the optimization is not monotonically minimizing the functional but keeps fluctuating. Interestingly, if the co-states `chis[k]` are exchanged by `-chis[k]`, the optimization indeed shows monotonic convergence in terms of a maximization of the Hilbert-Schmidt distance. Moreover, the optimization minimizes the functional correctly, if the real-part functional is used.

The implementations of the Hilbert-Schmidt distance and its co-states construction seem correct to me. Maybe a problem with the (non-?)convexity of the Hilbert-Schmidt distance?

**Comment by goerz** [comment]
Based on our discussion, this is not a bug, nor is the functional non-convex. The problem is simply that the two functionals result in a significantly different optimization landscape that requires different values for λₐ for numerical stability. However, it is challenging to really get to the bottom of this. We've seen examples where λₐ for `J_T_hs` has to be large than for `J_T_re`, and the other way around.

While our understanding of the different optimization landscapes is still imperfect, the best resolution is to tone down the recommendation for `J_T_hs` for *any* optimization using density matrices and to point out that changing the functional may require adjusting λₐ.

**Comment by christianekoch** [comment]
I fully agree with this work-around.
