### ISSUE TITLE
PDF of Documentation

### ISSUE THREAD

**Issue by TejasAvinashShetty** [qucontrol/krotov#52]
* Krotov version: stable
* Python version: 3.7
* Operating System: MacOS High sierra

### Description
I wanted to download a PDF version of the Documentation. But I couldn't find an option on the Readthe Docs site. I think you need to build the documentation at least once for me to download it. A great format for issues by the way 😃.   

### What I Did
Tried to download PDF of Documentation. What I expected 
[option on Read thedocs own Documentation site](https://www.icloud.com/iclouddrive/076nMFimgH7vHImPuYe5Niwhw#Read_thedocs_RTD)
What I found,
[Option on krotov Documentation site](https://www.icloud.com/iclouddrive/0_bAJi75CxUWzwHS7v8LTh3-Q#krotovRTD)

Sorry for the silly issue. I just have a problem with staring at the computer for too long. This would happen when reading the documentation on the computer.

**Comment by goerz** [comment]
Thank you for raising this issue! We consider accessibility as an important concern.

Unfortunately, though, I don't see any way to provide a full pdf documentation at this time. The Sphinx-pdf renderer cannot handle math, unicode, javascript, jupyter notebooks, or svg graphics, all of which are used throughout the documentation. The generated latex will not compile, and is not trivial to fix by hand. The epub generator (which could then be printed to pdf) is slightly better, but also cannot handle math, javascript, or jupyter notebooks. This is why these options on the RTD website are disabled. Sphinx' limitiations in this respect are extremely unfortunate. Non-HTML formats on Sphinx really only work for very simple documents.

Maybe there are solutions for generating pdfs from multi-page websites (via screenshots, I would suppose, if the mathjax-rendering of equations is supposed to work)? You might also try to view the documentation on an e-paper reader that has a built-in web browser (I tested this on a Kindle, and it works relatively well). I'll continue looking into this.

The more obvious route would be to read the pdf of the pre-print associated with the documentation (https://arxiv.org/abs/1902.11284, with an extended new version and final publication coming shortly). This would give you most of the background material, but not the API documentation.

I'm leaving this issue open, so that we can continue looking for solutions.

**Comment by TejasAvinashShetty** [comment]
Maybe instead of Read the docs, one can have the entire documentation written as a jupyter notebook. This can then be tracked via git using the various methods  already mentioned in the [Documentation](https://krotov.readthedocs.io/en/stable/02_contributing.html#how-to-make-git-diff-work-for-notebooks). Also Jupyter notebooks can be easily [rendered](https://stackoverflow.com/a/58256447/7952027) to a variety of formats including PDF.

**Comment by goerz** [comment]
@TejasAvinashShetty  I've had some success with getting the Sphinx documentation into a pdf format: [krotov.pdf](https://github.com/qucontrol/krotov/files/3709972/krotov.pdf).

In order to get the unicode and custom math macros to work, the key was to use lualatex instead of pdflatex, switch to a font with good unicode coverage (DejaVu), and do some post-processing on  the auto-generated latex code for the notebooks.

Please note that we just published a revision of the preprint describing the `krotov` package: https://arxiv.org/abs/1902.11284v4. I would recommend the preprint over the sections "Krotov's method" and "Other Optimization Methods" in [krotov.pdf](https://github.com/qucontrol/krotov/files/3709972/krotov.pdf). These parts of the  documentation will be updated in the near future based on the preprint, see #54.

For everything else (the API documentation and complete example notebooks), you can definitely use [krotov.pdf](https://github.com/qucontrol/krotov/files/3709972/krotov.pdf). It is unlikely that we'll be able to generate this pdf automatically on RTD for every commit, but the plan would be to make the pdf documentation available as a download on Github for all released versions starting from 1.0.

Assuming you have luatex and the necessary fonts installed on your (Linux/MacOS) system, you could also generate the pdf documentation yourself from a checkout of the `krotov` repository, by running `make docs-pdf`. This will result in [krotov.pdf](https://github.com/qucontrol/krotov/files/3709972/krotov.pdf) in `./docs/_build/tex/`.

**Comment by christianekoch** [comment]
It would be good to include these instructions with the docs.

**Comment by goerz** [comment]
Will do!

**Comment by goerz** [comment]
Official PDF documentation (as linked from the README) is now at https://github.com/qucontrol/krotov/tree/master/docs/pdf

**Comment by goerz** [comment]
Now that we've switched to documentation hosting to gh-pages/doctr, where I have full control, the PDF for [v1.0.0](https://qucontrol.github.io/krotov/v1.0.0/) can also be downloaded from the menu in the bottom left corner on the screen (like @TejasAvinashShetty asked for originally)

**Comment by TejasAvinashShetty** [comment]
Wonderful Dr @goerz . Thank you very much
